class AlterCreditumDatabase < ActiveRecord::Migration
  def up
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE ID_CASA_COMERCIAL id_casa_comercial int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE NIT nit varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE NOMBRE nombre varchar(60)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE RIF rif varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE UBICACION ubicacion varchar(100)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE CELULAR celular varchar(20)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE DIRECCION direccion varchar(50)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE EMAIL email varchar(50)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE FAX fax varchar(20)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE ID_CASA_COMERCIAL id_casa_comercial int(11)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE ID_CLIENTE id_cliente int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE NIT nit varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE NOMBRE nombre varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE RIF rif varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE TELEFONO telefono varchar(20)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE APORTES aportes int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE CONSULTAS consultas int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE DESCUENTO descuento int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE STATUS status int(1)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE FECHA_INI fecha_ini date;')
	Cliente.connection.execute('ALTER TABLE clientes_personas CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_personas CHANGE ID_CLIENTE_PERSONA id_cliente_persona int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_personas CHANGE ID_PERSONA id_persona varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE CEDULA_USUARIO cedula_usuario int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE FECHA_HORA fecha_hora datetime  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE ID_PERSONA id_persona varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE CEDULA_USUARIO cedula_usuario int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE FECHA_HORA fecha_hora datetime  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE ID_PERSONA id_persona varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE ESTADO estado tinyint(4)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE EXPERIENCIA experiencia tinyint(4)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE FACTURA factura varchar(20)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE ID id int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE ID_CLIENTE_PERSONA id_cliente_persona int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE MONTO monto double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE NUM_GIROS num_giros tinyint(4)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE PAGO_MES pago_mes double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE FECHA_COMPRA fecha_compra date;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE FECHA_OPERACION fecha_operacion date;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE CEDULA_USUARIO cedula_usuario int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE FECHA_HORA fecha_hora datetime  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE ID_FACTURA id_factura int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE ID_PERSONA id_persona varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE STATUS status int(1)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE direcciones CHANGE DIRECCION direccion varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE direcciones CHANGE ID_PERSONA id_persona varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE WEB web varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE PRECIO_OK1 precio_ok1 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE PRECIO_OK2 precio_ok2 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE PRECIO_OK3 precio_ok3 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE PRECIO_OK4 precio_ok4 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE PRECIO_FALLIDA precio_fallida float;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE DESCUENTO descuento int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE FALLIDAS fallidas int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE ID_FACTURA id_factura int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE PRECIO_FALLIDA precio_fallida double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE PRECIO_OK precio_ok double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE TOTAL total double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE TOTALD totald double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE TOTALF totalf double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE TOTALV totalv double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE VALIDAS validas int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE FECHA_DESDE fecha_desde date;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE FECHA_HASTA fecha_hasta date;')
	Cliente.connection.execute('ALTER TABLE nivel CHANGE DESCRIPCION descripcion varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE nivel CHANGE ID_NIVEL id_nivel tinyint(1) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE DIRECCION direccion varchar(100)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE EMAIL email varchar(30)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE FAX fax varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE NIT nit varchar(10)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE NOMBRE nombre varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE RIF rif varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE TELEFONO telefono varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE APELLIDO apellido varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE CEDULA cedula varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE CELULAR celular varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE NOMBRE nombre varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE PROFESION profesion varchar(16)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE TELEFONO telefono varchar(15)  NULL;')
	Cliente.connection.execute("ALTER TABLE personas_naturales CHANGE NACIONALIDAD nacionalidad ENUM('VENEZOLANO','EXTRANJERO') NULL DEFAULT 'VENEZOLANO' ;")
	Cliente.connection.execute("ALTER TABLE personas_naturales CHANGE SEXO sexo ENUM('M','F');")
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE FECHA_NAC fecha_nac date;')	
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE APELLIDO apellido varchar(20)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE CEDULA cedula int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE CELULAR celular varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE ID_CLIENTE id_cliente int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE ID_NIVEL id_nivel tinyint(1)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE NOMBRE nombre varchar(20)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE PWD pwd varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE TELEFONO telefono varchar(15)  NULL;')
	Cliente.connection.execute("ALTER TABLE usuarios CHANGE NACIONALIDAD nacionalidad ENUM('VENEZOLANO','EXTRANJERO') NULL DEFAULT 'VENEZOLANO' ;")
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE FECHA fecha date;')

  end

  def down
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE id_casa_comercial ID_CASA_COMERCIAL int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE nit NIT varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE nombre NOMBRE varchar(60)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE rif RIF varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE casas_comerciales CHANGE ubicacion UBICACION varchar(100)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE celular CELULAR varchar(20)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE direccion DIRECCION varchar(50)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE email EMAIL varchar(50)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE fax FAX varchar(20)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE id_casa_comercial ID_CASA_COMERCIAL int(11)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE id_cliente ID_CLIENTE int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE nit NIT varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE nombre NOMBRE varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE rif RIF varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes CHANGE telefono TELEFONO varchar(20)  NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE aportes APORTES int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE consultas CONSULTAS int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE descuento DESCUENTO int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE status STATUS int(1)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_conf CHANGE fecha_ini FECHA_INI date;')
	Cliente.connection.execute('ALTER TABLE clientes_personas CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_personas CHANGE id_cliente_persona ID_CLIENTE_PERSONA int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE clientes_personas CHANGE id_persona ID_PERSONA varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE cedula_usuario CEDULA_USUARIO int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE fecha_hora FECHA_HORA datetime  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas CHANGE id_persona ID_PERSONA varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE cedula_usuario CEDULA_USUARIO int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE fecha_hora FECHA_HORA datetime  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE consultas_fallidas CHANGE id_persona ID_PERSONA varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE estado ESTADO tinyint(4)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE experiencia EXPERIENCIA tinyint(4)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE factura FACTURA varchar(20)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE id ID int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE id_cliente_persona ID_CLIENTE_PERSONA int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE monto MONTO double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE num_giros NUM_GIROS tinyint(4)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE pago_mes PAGO_MES double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE fecha_compra FECHA_COMPRA date;')
	Cliente.connection.execute('ALTER TABLE creditos CHANGE fecha_operacion FECHA_OPERACION date;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE cedula_usuario CEDULA_USUARIO int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE fecha_hora FECHA_HORA datetime  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE id_factura ID_FACTURA int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE id_persona ID_PERSONA varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE detalle_facturas CHANGE status STATUS int(1)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE direcciones CHANGE direccion DIRECCION varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE direcciones CHANGE id_persona ID_PERSONA varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE web WEB varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE precio_ok1 PRECIO_OK1 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE precio_ok2 PRECIO_OK2 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE precio_ok3 PRECIO_OK3 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE precio_ok4 PRECIO_OK4 float;')
	Cliente.connection.execute('ALTER TABLE empresa_conf CHANGE precio_fallida PRECIO_FALLIDA float;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE descuento DESCUENTO int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE fallidas FALLIDAS int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE id_factura ID_FACTURA int(11) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE precio_fallida PRECIO_FALLIDA double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE precio_ok PRECIO_OK double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE total TOTAL double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE totald TOTALD double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE totalf TOTALF double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE totalv TOTALV double  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE validas VALIDAS int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE fecha_desde FECHA_DESDE date;')
	Cliente.connection.execute('ALTER TABLE facturas CHANGE fecha_hasta FECHA_HASTA date;')
	Cliente.connection.execute('ALTER TABLE nivel CHANGE descripcion DESCRIPCION varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE nivel CHANGE id_nivel ID_NIVEL tinyint(1) auto_increment NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE direccion DIRECCION varchar(100)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE email EMAIL varchar(30)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE fax FAX varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE nit NIT varchar(10)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE nombre NOMBRE varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE rif RIF varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_juridicas CHANGE telefono TELEFONO varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE apellido APELLIDO varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE cedula CEDULA varchar(15)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE celular CELULAR varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE nombre NOMBRE varchar(30)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE profesion PROFESION varchar(16)  NULL;')
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE telefono TELEFONO varchar(15)  NULL;')
	Cliente.connection.execute("ALTER TABLE personas_naturales CHANGE nacionalidad NACIONALIDAD ENUM('VENEZOLANO','EXTRANJERO') NULL DEFAULT 'VENEZOLANO' ;")
	Cliente.connection.execute("ALTER TABLE personas_naturales CHANGE sexo SEXO ENUM('M','F');")
	Cliente.connection.execute('ALTER TABLE personas_naturales CHANGE fecha_nac FECHA_NAC date;')	
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE apellido APELLIDO varchar(20)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE cedula CEDULA int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE celular CELULAR varchar(15)  NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE id_cliente ID_CLIENTE int(11)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE id_nivel ID_NIVEL tinyint(1)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE nombre NOMBRE varchar(20)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE pwd PWD varchar(50)  NOT NULL;')
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE telefono TELEFONO varchar(15)  NULL;')
	Cliente.connection.execute("ALTER TABLE usuarios CHANGE nacionalidad NACIONALIDAD ENUM('VENEZOLANO','EXTRANJERO') NULL DEFAULT 'VENEZOLANO' ;")
	Cliente.connection.execute('ALTER TABLE usuarios CHANGE fecha FECHA date;')
  end
end
